### PR TITLE
add missing elements.  add BE834 report.

### PR DESCRIPTION
**Pull request by kenberland**

### CODE REVIEW

**Comment by kenberland** [comment]
Oops.

**Comment by irobayna** [comment]
@kenberland  would you like to merge this ?

**Comment by kenberland** [comment]
I didn't mean to open it against your repo.  But yes, when finished, that would be nice.

I'm looking to write a test now.  `edi-pp` is happy with my test input now (no red, no invalid segments).  However, every file I try to read/parse this way:

```ruby
parser, result = parser.read(Stupidedi::Reader.build(input))`
```

yields this for `result`:

```ruby
Either.failure("reached end of input without finding a segment identifier")
```

**Comment by irobayna** [comment]
did you try changing the parser ```Config``` ?

you may try: ```default```, ```contrib``` or ```hipaa```

```config = Stupidedi::Config.default``` or
```config = Stupidedi::Config.contrib``` or
```config = Stupidedi::Config.hipaa```

be sure to try something like this:
```
config = Stupidedi::Config.contrib
parser = Stupidedi::Builder::StateMachine.build(config)
parser, result = parser.read(Stupidedi::Reader.build(input))
```

**Comment by kenberland** [comment]
Using dcc6c1e

```ruby
config = [Stupidedi::Config.hipaa, Stupidedi::Config.contrib, Stupidedi::Config.default]
config.each do |c|
  machine = Stupidedi::Builder::StateMachine.build(c)
  input = File.open('spec/fixtures/X221-HP835/1-good.txt', :encoding => 'ISO-8859-1')
  machine, result = machine.read(Stupidedi::Reader.build(input))
  p result
end
```

Yields:

```
Either.failure("reached end of input before finding ISA segment identifier")
Either.failure("reached end of input before finding ISA segment identifier")
Either.failure("reached end of input before finding ISA segment identifier")
```

**Comment by kputnam** [comment]
I think this is normal behavior, essentially indicating it reached the EOF. There should be a method called `fatal?` on `result` that returns false. Your error looks different than mine (below), but I think this is because I used `pp` while you used `p`. Can you see if using `pp` gives you more detail?

```
Result.failure(
  "reached end of input before finding ISA segment identifier",
  FileInput("\n" at line 40, column 17, offset 1523, file 1-good.txt),
  non-fatal)
```

**Comment by kenberland** [comment]
Understood.  I'll dig deeper.  Seems like there should be a `#read`-like method than returns success.

**Comment by kputnam** [comment]
Yeah, possibly. I waffled on that (a long time ago) and agree it's a little strange, but at the time I came to the decision the caller has all the information needed to handle this situation: `result.fatal?` will be `false` and `machine` can be queried to see that it's on an `IEA` segment (the end an `ISA`...`IEA` envelope), so it definitely parsed something -- you can conclude that using other methods too.

If the parse tree (`machine`) were empty, this still might not be a fatal error, since it's possible the parser was fed non-X12. We had X12 messages from trading partners that were interleaved with non-X12 data, and the standard is silent on this, so I leaned toward not-fatal. So why is it an error at all? Probably because of implementation details, not any philosophical reason, but it's been a long time!

**Pull request closed without merging**
