### PR TITLE
Add support for HC837i

### PR DESCRIPTION
**Pull request by pepito2k**

### CODE REVIEW

**Comment by mistidoi** [comment]
👍

**Comment by mistidoi** [comment]
Doesn't one need to register the transaction set in `lib/stupidedi/config.rb`?

**Comment by kputnam** [comment]
Nice! I'll take a look and plan to merge this sometime this week (sorry for the delay). Oh, and like @mistidoi mentioned, you can add a reference to the configuration in the [`Configuration.hippa`](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/config.rb#L97) constructor

**Comment by pepito2k** [comment]
Reference added, please let me know if there's anything else needed.

**Comment by pepito2k** [comment]
@kputnam any chance to review this ?

**Comment by kputnam** [comment]
Sorry for taking forever, I have looked at it and will merge it this weekend! Thanks for the nudge ;-)

**Comment by kputnam** [comment]
Thanks @pepito2k!

**Pull request merged**
